
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MarketHelp
{

using System;
    using System.Collections.Generic;
    
public partial class Artikli
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Artikli()
    {

        this.Dobavljaci_artikala = new HashSet<Dobavljaci_artikala>();

        this.Stavke_dokumenta = new HashSet<Stavke_dokumenta>();

    }


    public int id_artikla { get; set; }

    public string naziv { get; set; }

    public int kolicina { get; set; }

    public double cijena { get; set; }

    public Nullable<System.DateTime> rok_trajanja { get; set; }

    public Nullable<int> min_kolicina { get; set; }

    public Nullable<int> max_kolicina { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Dobavljaci_artikala> Dobavljaci_artikala { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Stavke_dokumenta> Stavke_dokumenta { get; set; }

}

}
