
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MarketHelp
{

using System;
    using System.Collections.Generic;
    
public partial class Dokumenti
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Dokumenti()
    {

        this.Stavke_dokumenta = new HashSet<Stavke_dokumenta>();

    }


    public int id_dokumenta { get; set; }

    public string korisnicko_ime { get; set; }

    public int nacin_placanja { get; set; }

    public string suradnik { get; set; }

    public System.DateTime datum { get; set; }

    public string napomena { get; set; }

    public Nullable<double> iznos_racuna { get; set; }

    public Nullable<double> popust { get; set; }

    public Nullable<int> realiziran { get; set; }



    public virtual Korisnici Korisnici { get; set; }

    public virtual Nacini_placanja Nacini_placanja { get; set; }

    public virtual Suradnici Suradnici { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Stavke_dokumenta> Stavke_dokumenta { get; set; }

}

}
