

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MarketHelp
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class BazaProjekta2 : DbContext
{
    public BazaProjekta2()
        : base("name=BazaProjekta2")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Artikli> Artikli { get; set; }

    public virtual DbSet<Dobavljaci_artikala> Dobavljaci_artikala { get; set; }

    public virtual DbSet<Dokumenti> Dokumenti { get; set; }

    public virtual DbSet<Korisnici> Korisnici { get; set; }

    public virtual DbSet<Nacini_placanja> Nacini_placanja { get; set; }

    public virtual DbSet<Stavke_dokumenta> Stavke_dokumenta { get; set; }

    public virtual DbSet<Suradnici> Suradnici { get; set; }

    public virtual DbSet<Uloge_korisnika> Uloge_korisnika { get; set; }

    public virtual DbSet<Place> Place { get; set; }

    public virtual DbSet<Vrsta_dokumenta> Vrsta_dokumenta { get; set; }

}

}

