
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MarketHelp
{

using System;
    using System.Collections.Generic;
    
public partial class Stavke_dokumenta
{

    public int id_dokumenta { get; set; }

    public int id_artikla { get; set; }

    public int kolicina { get; set; }



    public virtual Artikli Artikli { get; set; }

    public virtual Dokumenti Dokumenti { get; set; }

}

}
