
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MarketHelp
{

using System;
    using System.Collections.Generic;
    
public partial class Suradnici
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Suradnici()
    {

        this.Dobavljaci_artikala = new HashSet<Dobavljaci_artikala>();

        this.Dokumenti = new HashSet<Dokumenti>();

    }


    public string oib { get; set; }

    public string naziv { get; set; }

    public string adresa { get; set; }

    public string kontakt { get; set; }

    public string napomena { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Dobavljaci_artikala> Dobavljaci_artikala { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Dokumenti> Dokumenti { get; set; }

}

}
