
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MarketHelp
{

using System;
    using System.Collections.Generic;
    
public partial class Uloge_korisnika
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Uloge_korisnika()
    {

        this.Korisnici = new HashSet<Korisnici>();

    }


    public int id_uloge { get; set; }

    public string naziv { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Korisnici> Korisnici { get; set; }

}

}
